"""
Django settings for WoS project.

Generated by 'django-admin startproject' using Django X.X.X.

For more information on this file, see
https://docs.djangoproject.com/en/X.X/topics/settings/

"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/X.X/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h]

# CSRF settings for production
# Set CSRF_TRUSTED_ORIGINS to your domain(s), e.g., "https://example.com,https://www.example.com"
_csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins_env.split(',') if o.strip()]

# Debug: print what we got
print(f"[Settings] CSRF_TRUSTED_ORIGINS from env: '{_csrf_origins_env}' -> {CSRF_TRUSTED_ORIGINS}")

# If no trusted origins specified but ALLOWED_HOSTS is set, auto-generate from ALLOWED_HOSTS
if not CSRF_TRUSTED_ORIGINS and ALLOWED_HOSTS and '*' not in ALLOWED_HOSTS:
    # Generate both http and https versions for each allowed host
    for host in ALLOWED_HOSTS:
        if host and not host.startswith('.'):
            CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
    print(f"[Settings] CSRF_TRUSTED_ORIGINS auto-generated: {CSRF_TRUSTED_ORIGINS}")

# Proxy settings - trust X-Forwarded-Proto header from reverse proxy (Traefik, nginx, etc.)
if os.environ.get('DJANGO_SECURE_PROXY_SSL_HEADER', '').lower() in ('1', 'true', 'yes'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Also set these for better security behind proxy
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# Cookie settings for HTTPS behind proxy
if not DEBUG:
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'true').lower() in ('1', 'true', 'yes')
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'true').lower() in ('1', 'true', 'yes')

# For private apps behind authenticated reverse proxy, CSRF can be disabled
CSRF_DISABLED = os.environ.get('CSRF_DISABLE', '').lower() in ('1', 'true', 'yes')
print(f"[Settings] CSRF_DISABLE={os.environ.get('CSRF_DISABLE', '')} -> CSRF_DISABLED={CSRF_DISABLED}")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backlog',  # Add your app here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Remove CSRF middleware if disabled (for private apps behind authenticated proxy)
if CSRF_DISABLED:
    MIDDLEWARE = [m for m in MIDDLEWARE if 'csrf' not in m.lower()]

ROOT_URLCONF = 'wos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wos.wsgi.application'

# Database
# https://docs.djangoproject.com/en/X.X/ref/settings/#databases
# Use DATABASE_PATH env var if set, otherwise default to db.sqlite3 in BASE_DIR

DATABASE_PATH = os.environ.get('DATABASE_PATH', str(BASE_DIR / 'db.sqlite3'))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_PATH,
    }
}

# Password validation
# https://docs.djangoproject.com/en/X.X/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/X.X/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/X.X/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Where collectstatic will put files (served via reverse proxy in production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/X.X/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
