# Generated by Django 3.2.25 on 2025-12-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_auto_20251222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='workitems',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='valuefactoranswer',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='StoryValueFactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backlog.valuefactoranswer')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='backlog.story')),
                ('valuefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='backlog.valuefactor')),
            ],
            options={
                'unique_together': {('story', 'valuefactor')},
            },
        ),
    ]
