# Generated by Django 3.2.25 on 2025-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0006_auto_20251222_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('refined', 'Refined')], default='new', max_length=20),
        ),
    ]
