# Generated by Django 3.2.25 on 2025-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0007_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blocked',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
