# Generated by Django 3.2.25 on 2025-12-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0009_story_planned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='target',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
    ]
