# Generated by Django 3.2.25 on 2025-12-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0012_add_archive_and_review_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='backlog.story')),
            ],
            options={
                'verbose_name': 'story history',
                'verbose_name_plural': 'story histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
