# Generated by Django 3.2.25 on 2025-12-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_valuefactor_valuefactorsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuefactor',
            name='score',
        ),
        migrations.CreateModel(
            name='ValueFactorAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valuefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backlog.valuefactor')),
            ],
            options={
                'verbose_name': 'valuefactor answer',
                'verbose_name_plural': 'valuefactor answers',
            },
        ),
    ]
