# Generated by Django 3.2.25 on 2025-12-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_auto_20251222_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.AlterField(
            model_name='story',
            name='target',
            field=models.TextField(blank=True),
        ),
    ]
