# Generated by Django 3.2.25 on 2025-12-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0005_auto_20251222_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'costfactor',
                'verbose_name_plural': 'costfactors',
            },
        ),
        migrations.CreateModel(
            name='CostFactorAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backlog.costfactor')),
            ],
            options={
                'verbose_name': 'costfactor answer',
                'verbose_name_plural': 'costfactor answers',
            },
        ),
        migrations.CreateModel(
            name='CostFactorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'costfactor section',
                'verbose_name_plural': 'costfactor sections',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='costfactor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costfactors', to='backlog.costfactorsection'),
        ),
        migrations.CreateModel(
            name='StoryCostFactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backlog.costfactoranswer')),
                ('costfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='backlog.costfactor')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_scores', to='backlog.story')),
            ],
            options={
                'unique_together': {('story', 'costfactor')},
            },
        ),
    ]
