# Generated by Django 3.2.25 on 2025-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0008_auto_20251223_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='planned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
