# Generated by Django 3.2.25 on 2025-12-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0010_rename_target_to_goal_remove_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='backlog.story')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='backlog.story')),
            ],
            options={
                'verbose_name': 'story dependency',
                'verbose_name_plural': 'story dependencies',
                'unique_together': {('story', 'depends_on')},
            },
        ),
    ]
