# Generated by Django 3.2.25 on 2025-12-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0011_add_story_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='review_required',
            field=models.BooleanField(default=False),
        ),
    ]
