# Generated by Django 3.2.25 on 2026-01-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0013_add_story_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costfactor',
            options={'ordering': ['section__name', 'name'], 'verbose_name': 'cost factor', 'verbose_name_plural': 'cost factors'},
        ),
        migrations.AlterModelOptions(
            name='costfactoranswer',
            options={'ordering': ['costfactor', 'score'], 'verbose_name': 'cost factor answer', 'verbose_name_plural': 'cost factor answers'},
        ),
        migrations.AlterModelOptions(
            name='costfactorsection',
            options={'ordering': ['name'], 'verbose_name': 'cost factor section', 'verbose_name_plural': 'cost factor sections'},
        ),
        migrations.AlterModelOptions(
            name='storycostfactorscore',
            options={'verbose_name': 'story cost score', 'verbose_name_plural': 'story cost scores'},
        ),
        migrations.AlterModelOptions(
            name='storyhistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'story history', 'verbose_name_plural': 'story history entries'},
        ),
        migrations.AlterModelOptions(
            name='storyvaluefactorscore',
            options={'verbose_name': 'story value score', 'verbose_name_plural': 'story value scores'},
        ),
        migrations.AlterModelOptions(
            name='valuefactor',
            options={'ordering': ['section__name', 'name'], 'verbose_name': 'value factor', 'verbose_name_plural': 'value factors'},
        ),
        migrations.AlterModelOptions(
            name='valuefactoranswer',
            options={'ordering': ['valuefactor', 'score'], 'verbose_name': 'value factor answer', 'verbose_name_plural': 'value factor answers'},
        ),
        migrations.AlterModelOptions(
            name='valuefactorsection',
            options={'ordering': ['name'], 'verbose_name': 'value factor section', 'verbose_name_plural': 'value factor sections'},
        ),
        migrations.AlterField(
            model_name='costfactor',
            name='description',
            field=models.TextField(blank=True, help_text='Explains what this factor measures'),
        ),
        migrations.AlterField(
            model_name='costfactoranswer',
            name='description',
            field=models.CharField(blank=True, help_text='Human-readable answer text', max_length=400),
        ),
        migrations.AlterField(
            model_name='costfactoranswer',
            name='score',
            field=models.IntegerField(help_text='Numeric score for this answer'),
        ),
        migrations.AlterField(
            model_name='storycostfactorscore',
            name='answer',
            field=models.ForeignKey(blank=True, help_text='None means undefined/not yet scored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backlog.costfactoranswer'),
        ),
        migrations.AlterField(
            model_name='storyhistory',
            name='field_name',
            field=models.CharField(help_text='Name of the changed field', max_length=100),
        ),
        migrations.AlterField(
            model_name='storyvaluefactorscore',
            name='answer',
            field=models.ForeignKey(blank=True, help_text='None means undefined/not yet scored', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='backlog.valuefactoranswer'),
        ),
        migrations.AlterField(
            model_name='valuefactor',
            name='description',
            field=models.TextField(blank=True, help_text='Explains what this factor measures'),
        ),
        migrations.AlterField(
            model_name='valuefactoranswer',
            name='description',
            field=models.CharField(blank=True, help_text='Human-readable answer text', max_length=400),
        ),
        migrations.AlterField(
            model_name='valuefactoranswer',
            name='score',
            field=models.IntegerField(help_text='Numeric score for this answer'),
        ),
    ]
