# Generated by Django 5.2.9 on 2026-01-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0014_allow_null_answer_for_undefined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color code (e.g., #2563eb)', max_length=7)),
                ('icon', models.CharField(default='🏷️', help_text='Emoji or short icon symbol', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'label category',
                'verbose_name_plural': 'label categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='stories', to='backlog.label'),
        ),
        migrations.AddField(
            model_name='label',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='backlog.labelcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('category', 'name')},
        ),
    ]
