# Generated by Django 5.2.9 on 2026-01-04 16:28

from django.db import migrations


def create_epic_labels(apps, schema_editor):
    """Create a label category 'Epics' and a label for each epic, then assign to stories."""
    LabelCategory = apps.get_model('backlog', 'LabelCategory')
    Label = apps.get_model('backlog', 'Label')
    Epic = apps.get_model('backlog', 'Epic')
    Story = apps.get_model('backlog', 'Story')

    # Create the Epics label category
    category, _ = LabelCategory.objects.get_or_create(
        name='Epics',
        defaults={
            'color': '#6366f1',  # Indigo color
            'icon': 'mdi-book-open-page-variant',
        }
    )

    # Create a label for each epic and assign to its stories
    for epic in Epic.objects.all():
        label, _ = Label.objects.get_or_create(
            category=category,
            name=epic.title,
            defaults={
                'description': f'Stories belonging to epic: {epic.title}',
            }
        )
        # Add this label to all stories in the epic
        for story in Story.objects.filter(epic=epic):
            story.labels.add(label)


def reverse_epic_labels(apps, schema_editor):
    """Remove the Epics category and its labels."""
    LabelCategory = apps.get_model('backlog', 'LabelCategory')
    
    try:
        category = LabelCategory.objects.get(name='Epics')
        # Labels will be deleted via cascade, and M2M relations will be cleaned up
        category.delete()
    except LabelCategory.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0015_add_labels'),
    ]

    operations = [
        migrations.RunPython(create_epic_labels, reverse_epic_labels),
    ]
