# Generated by Django 5.2.9 on 2026-01-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0016_populate_epic_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='epic',
        ),
        migrations.DeleteModel(
            name='Epic',
        ),
    ]
