# Generated by Django 5.2.9 on 2026-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0017_remove_epic_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['title'], 'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='finished',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='planned',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['archived', 'status'], name='story_archived_status_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['archived', 'created_at'], name='story_archived_created_idx'),
        ),
    ]
