# Generated by Django 5.2.9 on 2026-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0018_add_story_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycostfactorscore',
            name='relative_rank',
            field=models.IntegerField(blank=True, help_text='Relative ranking within this factor (1 = lowest cost, None = not ranked)', null=True),
        ),
        migrations.AddField(
            model_name='storyvaluefactorscore',
            name='relative_rank',
            field=models.IntegerField(blank=True, help_text='Relative ranking within this factor (1 = highest, None = not ranked)', null=True),
        ),
    ]
