# Generated by Django 5.2.9 on 2026-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0019_add_relative_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='costfactor',
            name='scoring_mode',
            field=models.CharField(choices=[('absolute', 'Absolute (use answer score)'), ('relative', 'Relative (use ranking)')], default='absolute', help_text='How this factor contributes to the score: absolute uses answer scores, relative uses rankings', max_length=10),
        ),
        migrations.AddField(
            model_name='valuefactor',
            name='scoring_mode',
            field=models.CharField(choices=[('absolute', 'Absolute (use answer score)'), ('relative', 'Relative (use ranking)')], default='absolute', help_text='How this factor contributes to the score: absolute uses answer scores, relative uses rankings', max_length=10),
        ),
    ]
